language: elixir
elixir:
  - 1.2.6
otp_release:
  - 18.1
notifications:
  recipients:
    - scott@kidder.io
before_script:
  - export PATH=`pwd`/elixir/bin:$PATH
  - mix local.hex --force
  - MIX_ENV=test mix do deps.get, compile
script:
  - mix test
after_success:
  - "mix compile && mix coveralls.travis"
env:
  - MIX_ENV=test
